/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utp.misiontic2022.c2.utp.misiontic2022.c2.p41.reto4.vista;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import utp.misiontic2022.c2.utp.misiontic2022.c2.p41.reto4.modelo.vo.Requerimiento_1;
import utp.misiontic2022.c2.utp.misiontic2022.c2.p41.reto4.util.ControladorRequerimientos;

/**
 *
 * @author Usuario
 */
public class Requerimiento_1tabla extends javax.swing.JFrame {
    
    private DefaultTableModel modeloTabla;
    public static final ControladorRequerimientos controlador = new ControladorRequerimientos();

    /**
     * Creates new form Requerimiento_1tabla
     */
    public Requerimiento_1tabla() {
        initComponents();
        modeloTabla= new DefaultTableModel();
        modeloTabla.addColumn("Nro. Líderes");
        modeloTabla.addColumn("Ciudad Residencia");
        TablaRequerimiento1.setModel(modeloTabla);
    }
    /**
        public void informacion(ArrayList<Requerimiento_1> info){
        String encabezados[] ={"Nro. Líderes", "Ciudad Residencia"};
        String matriz[][]= new String[info.size()][encabezados.length];
        for (int i =0; i< info.size(); i++){
            matriz[i][0] = info.get(i).getNro_lideres()+"";
            matriz[i][1] = info.get(i).getCiudad_residencia()+"";
        }
        TablaRequerimiento1 = new JTable(matriz, encabezados);
        TablaRequerimiento1.setColumnSelectionAllowed(true);
        TablaRequerimiento1.getColumnModel().getColumn(0).setPreferredWidth(20*jScrollPane1.getWidth()/100);
        TablaRequerimiento1.getColumnModel().getColumn(1).setPreferredWidth(80*jScrollPane1.getWidth()/100);
        jScrollPane1.setViewportView(TablaRequerimiento1);
        TablaRequerimiento1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
       
    } 
    **/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaRequerimiento1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Requerimiento1");

        TablaRequerimiento1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaRequerimiento1.setMaximumSize(new java.awt.Dimension(300, 64));
        jScrollPane1.setViewportView(TablaRequerimiento1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Requerimiento 1. Número de líderes y ciudad");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void GenerarT(){
        try {
            ArrayList<Requerimiento_1> numLideresCiudad = controlador.consultarRequerimiento1();
            for (int i = 0; i < numLideresCiudad.size(); i++) {
                String datos[]= new String[2];
                datos[0]= "" + numLideresCiudad.get(i).getNro_lideres();
                datos[1]= numLideresCiudad.get(i).getCiudad_residencia();
                modeloTabla.addRow(datos);
                
            } 
        } catch (SQLException ex) {
            Logger.getLogger(Requerimiento_1tabla.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaRequerimiento1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
