/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utp.misiontic2022.c2.utp.misiontic2022.c2.p41.reto4.vista;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import utp.misiontic2022.c2.utp.misiontic2022.c2.p41.reto4.modelo.vo.Requerimiento_2;
import utp.misiontic2022.c2.utp.misiontic2022.c2.p41.reto4.util.ControladorRequerimientos;

/**
 *
 * @author Usuario
 */
public class Requerimiento_2tabla extends javax.swing.JFrame {
    
    private DefaultTableModel modeloTabla;
    public static final ControladorRequerimientos controlador = new ControladorRequerimientos();

    /**
     * Creates new form Requerimiento_2
     */
    public Requerimiento_2tabla() {
        initComponents();
        modeloTabla= new DefaultTableModel();
        modeloTabla.addColumn("ID proyecto");
        modeloTabla.addColumn("Proveedor");
        modeloTabla.addColumn("Pagado");
        modeloTabla.addColumn("ID Materialde Construcción");
        modeloTabla.addColumn("Nombre Material");
        TablaRequerimiento2.setModel(modeloTabla);
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaRequerimiento2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Requerimiento2");

        TablaRequerimiento2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "col1", "col2", "col3", "col4", "col5"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaRequerimiento2.setMaximumSize(new java.awt.Dimension(300, 300));
        jScrollPane1.setViewportView(TablaRequerimiento2);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Requerimiento 2. Materiales no pagos a Homecenter");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void GenerarT(){
        try {
            ArrayList<Requerimiento_2> materialesNoPagados = controlador.consultarRequerimiento2();
            for (int i = 0; i < materialesNoPagados.size(); i++) {
                String datos[]= new String[5];
                datos[0]= "" + materialesNoPagados.get(i).getID_proyecto();
                datos[1]= materialesNoPagados.get(i).getProveedor();
                datos[2]= materialesNoPagados.get(i).getPagado();
                datos[3]= "" + materialesNoPagados.get(i).getID_material_construccion();
                datos[4]= materialesNoPagados.get(i).getNombre_material();
                modeloTabla.addRow(datos);
                
            } 
        } catch (SQLException ex) {
            Logger.getLogger(Requerimiento_1tabla.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaRequerimiento2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
